version: '3.1'
services:  
    postgres:    
      image: postgres    
      environment:
        POSTGRES_DB: "crud"
        POSTGRES_USER: "admin"      
        POSTGRES_PASSWORD: "admin"    
      
      ports:
        - "5432:5432"